all:
  children:
    dns_servers:
      hosts:
        pihole.dns.puvvadi.net:
        guard.dns.puvvadi.net:
        dns.puvvadi.net:
    docker_hosts:
      hosts:
        docker.dns.puvvadi.net:
        pihole.dns.puvvadi.net:
        guard.dns.puvvadi.net:
        dns.puvvadi.net:
        media.puvvadi.net:
        metrics.dns.puvvadi.net:
    iot_management:
      hosts:
        esphome.dns.puvvadi.net:
    esphome:
      hosts:
        esphome.dns.puvvadi.net:
    bind: 
      hosts:
        dns.puvvadi.net:
